# remark:用户模块 author:lianghb date:2019-05-21
server:
  port: 9008

spring:
  profiles:
#    active: #spring.profiles.active#
    active: dev
  jackson:
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml


